### ISSUE TITLE
Plugin fails with valid OpenAPI spec

### ISSUE THREAD

**Issue by sergioalvz** [krakenjs/hapi-openapi#117]
Hi there,

first of all, thanks for this amazing project :)

This is more a question than an issue itself but it is not possible to make the [PetStore](http://petstore.swagger.io/v2/swagger.json) definition to work with this plugin because `POST /v2/pet` has an empty description `''` (which does not look to be a valid value for Hapi's `route.options.description`). Since the document is a valid OpenAPI spec, perhaps it might be better to skip the description property for `route.options` in those cases... What do you think?

Cheers,
Sergio

**Comment by tlivings** [comment]
Sounds good. If none is provided it should definitely not worry about it.

I just added it for the case where haps docs are generated (rare).

**Comment by sergioalvz** [comment]
@tlivings do you mind if I open a PR for this?

**Comment by tlivings** [comment]
This is published in 1.0.1.

**Comment by tlivings** [comment]
Thanks for the PR.
