### ISSUE TITLE
swagger-ui integration

### ISSUE THREAD

**Issue by ijohnson888** [krakenjs/hapi-openapi#119]
I'm trying to find an example of swagger-ui integration with this module. I have a basic service setup, but the problem I am running into is that the swagger link returns the raw swagger definition, not the swagger-ui. Having read through the code, it appears that this would be expected behavior. Do you have any documentation or examples on how to get the swagger-ui integrated? Thank you.

**Comment by tlivings** [comment]
You simply load swagger-UI site separately and point it at the url for the api-docs of your API.

Swagger-UI is meant for exploring multiple APIs, so apis generally will not embed it.

If you need further help I’m happy to provide more detail on getting it working (but the easiest way is just downloading swagger-UI and opening the index.html).

**Comment by ijohnson888** [comment]
Thank you. Now that I understand hapi-openapi's approach, I was able to integrate this with hapi-swaggered-ui without issue to accomplish our end goal. Thanks again.
