### ISSUE TITLE
Is this project listed on the main hapi site?

### ISSUE THREAD

**Issue by thejones** [krakenjs/hapi-openapi#122]
I stumbled upon this looking for something else on the kraken.js github. I did not see it listen on the main hapi site with the other swagger plugins/generators. If not, should it be? Excited to try it out!

**Comment by tlivings** [comment]
Probably!

**Comment by tlivings** [comment]
Added it: https://github.com/hapijs/hapijs.com/pull/575

Thanks for the reminder!
