### ISSUE TITLE
Unable to change payload options

### ISSUE THREAD

**Issue by Nox-404** [krakenjs/hapi-openapi#137]
Hello,

In the current version, we can't set the options for the payload from the OpenApi document with `X-Hapi-Options` as the `payload` options are overwritten. This can lead to a lot of hassle when you need a file upload route or to handle other formats (which requires `parse` option to be false)

I pushed a PR a few weeks ago #136, if you could look into it !

Thanks

**Comment by tlivings** [comment]
Addressed in `v1.1.0`.
