### ISSUE TITLE
[enhancement] better cors support

### ISSUE THREAD

**Issue by dcharbonnier** [krakenjs/hapi-openapi#159]
Build CORS for a route based on the declaration (https://hapijs.com/api/18.3.1#-routeoptionscors):
```
headers: ["Accept", "Authorization", "Content-Type", "If-None-Match"],
exposedHeaders: ["x-count", "link"]
```

Possible CORS headers (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
```
Access-Control-Allow-Credentials
Access-Control-Allow-Headers
Access-Control-Allow-Methods
Access-Control-Allow-Origin
Access-Control-Expose-Headers
Access-Control-Max-Age
Access-Control-Request-Headers
Access-Control-Request-Method
```

**Comment by tlivings** [comment]
This is fixed by https://github.com/krakenjs/hapi-openapi/pull/158 no?

**Comment by dcharbonnier** [comment]
#158 is at the server lever this is to implement it at the route level
