### ISSUE TITLE
Root level security not respected

### ISSUE THREAD

**Issue by DanielAnfelt** [krakenjs/hapi-openapi#162]
In the specification found at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md, it is stated `A declaration of which security schemes are applied for the API as a whole. The list of values describes alternative security schemes that can be used (that is, there is a logical OR between the security requirements). Individual operations can override this definition.`
This is not respected in `hapi-openapi`, as far as I can see.

I would expect this to happen in `hapi-openapi/lib/routes.js`.

**Comment by DanielAnfelt** [comment]
As the project seems to be a bit dead, I'm not even going to write up a fix for this, but just leave this issue here as documentation of the known flaw.

**Comment by tlivings** [comment]
I wouldn't say it is dead — just on a slow burn development-wise. Still used both at PayPal internally afaik, as well as Vrbo and other smaller companies.

Thanks for reporting the issue. Will try to get to it soon but would love a PR.

**Comment by DanielAnfelt** [comment]
Nice! Yeah, I can write up a PR. You will have it later this week.

**Comment by DanielAnfelt** [comment]
The week passed… finally had a little bit of spare time. How do I deliver?

**Comment by tlivings** [comment]
Send a PR for a free review 😊

**Comment by DanielAnfelt** [comment]
I'm afraid you'll have to guide me a bit here. I'm not allowed to push code to the repository. How do I send you the PR? :/
(Obvious beginner at contributing to anything outside of my organisation)
